default_stages: [pre-commit]
exclude: "CHANGELOG.md"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace # Trim whitespace from end of each line
      - id: end-of-file-fixer # All files only end in newline
      - id: check-yaml # verify yaml syntax
        args: [--allow-multiple-documents]
      - id: check-added-large-files # prevent extremely large files from being committed
        args: [--maxkb=10000]
      - id: mixed-line-ending # force linux line endings
        args: [--fix=lf]
      - id: check-ast # validates python files
      - id: check-merge-conflict # prevent merge conflict strings
      - id: check-case-conflict # prevent file namings that would fail on case insensitive file systems
      - id: check-docstring-first # checks a common error of defining a docstring after code
      - id: check-toml # validates toml files
      - id: debug-statements # validates there are no debugger imports
      - id: detect-private-key
      - id: name-tests-test # ensures test files are named correctly
        args: [--pytest-test-first]
      - id: check-json
      # - id: pretty-format-json
      # args: [--autofix]
      - id: check-shebang-scripts-are-executable
  # Regex-based pre-commit hooks to fix common errors
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa # enforce noqa occurs with specific codes
      - id: python-check-blanket-type-ignore # enforce type ignore is specific
      - id: python-check-mock-methods # prevent common mock mistakes
      - id: python-no-eval # prevent eval() function
      - id: python-no-log-warn # logger.warn is deprecated
      - id: python-use-type-annotations # enforce python3.6+ type annotations
      - id: rst-backticks # common mistake of single backticks when writing rst
      - id: rst-directive-colons # common mistake of directive not ending with double colon
      - id: rst-inline-touching-normal # mistake of inline code touching normal text in rst
  # Python encoding
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
  # Check for common spelling errors
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [-w]
  # Validate poetry
  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-poetry
  # Fix markdown lints
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
        args: ["--fix"]
  # Try to detect strings that are likely to be passwords or secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: (WORKSPACE)|(.*lock)
  # Define python format
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.5.6"
    hooks:
      - id: ruff
        args: ["--fix"]
  # Static type checking
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        types: [python]
        args: ["--exclude", ".tox,.eggs,tests,test_*,venv"]
  # Conventional Commit
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
